### PR TITLE
Gt clinical tables vignette

### PR DESCRIPTION
**Pull request by alex-lauer**
# Summary

I created a mock-up ADaM subject level dataset and vignette (article) to outline the necessary steps to create a demographic summary table and event rate analysis table with **gt**.

# Related GitHub Issues and PRs

- Ref:  None

# Checklist

- [ x ] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).
- [ ] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [ ] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by alex-lauer** [comment]
Hi Rich, thanks for supporting me on this project and letting me participate. {gt} is amazing - thank you so much!

**Comment by rich-iannone** [comment]
> Hi Rich, thanks for supporting me on this project and letting me participate. {gt} is amazing - thank you so much!

You’re welcome and I definitely appreciate the work you put into this vignette/article (many others reading it will feel the same)!

**Comment by alex-lauer** [comment]
Hi @rich-iannone, I finally added a description for gt_adsl in datasets.R. Thanks again for all your support!

**Comment by rich-iannone** [comment]
Could we add you as author in DESCRIPTION? If you're okay with that, put in your citation after Ellis Hughes' in this form:

```
    person("<first name>", "<family name>", , "<email address>", "aut",
           comment = c(ORCID = "<orcid id>"))
```

**Review by rich-iannone — APPROVED** [review]
lgtm and thanks so much for all of this!

**Pull request merged**
