### PR TITLE
Add tests for `cols_units()` and fix edge case + improve error messages for `cells_grand_summary()`

### PR DESCRIPTION
**Pull request by olivroy**
# Summary

Since it could detect the end of the string in `unit`, this would fail

```r
library(gt)
d <- data.frame(col1 = 1, col2 = 2)
d |> gt() |> cols_units(everything() ~ "1")
#> Error in if (column_pattern == "" && grepl(units, column_label, fixed = TRUE)) { : 
#>   missing value where TRUE/FALSE needed
```

due to the fact that the gsub part is TRUE.

Let me know if you want me to buildignore the `cols_units()` tests.

As always, this occured randomly to me. None of this is related to what I intended to do in the first place, but caught previous mistakes (made by me) and some unfound stuff!

# Related GitHub Issues and PRs

Also improve some messages and add some basic checking of input.

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [x] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by olivroy** [comment]
@rich-iannone is it possible to have a gt group and display tables side-by-side? I couldn't find much examples of  `gt_group()`

**Comment by rich-iannone** [comment]
@olivroy There's nothing built in to make this possible, though it seems like would be a really nice feature down the road.

**Comment by rich-iannone** [comment]
@olivroy We should do exactly this: https://github.com/rstudio/gt/issues/1288

**Pull request merged**
