### PR TITLE
Latex tab styles

### PR DESCRIPTION
**Pull request by kbrevoort**
# Summary

This pull request contains improvements that cause the font-size setting selected by the user through calls to `tab_options` or `tab_styles` to be reflected in PDF output (#1472).  While I was at it, I also implemented several other tab_style options that either had not yet been implemented or that was incompletely implemented.  These include underlining, italicizing bolding, indenting text, coloring text, filling cell backgrounds, and changing the text cases (i.e., uppercase, lowercase, sentence case).  While I was not able to get all of the features implemented, I think I have implemented the most important ones.

## Minimal Working Example

Consider the following Quarto document which generates both HTML and PDF output.

```
---
title: "Font Size"
format: 
  html: default
  pdf: 
    keep-tex: TRUE
---

## Quarto

Here is @tbl-fontTable.

```{r}
#| label: tbl-fontTable
#| tbl-cap: Table Demonstrating Font Sizes
#| echo: false

library(gt)


gt(exibble[1:5, c(1:3, 5:9)],
   rowname_col = 'row',
   groupname_col = 'group') |>
  tab_stubhead(label = 'stubhead') |>
  tab_spanner(label = 'heading',
              id = 'a1',
              columns = 1:3) |>
  tab_spanner(label = 'heading',
              id = 'b2',
              columns = 5:6) |>
  summary_rows(fns = list(list(label = 'Total', fn = 'sum'),
                          list(label = 'Avg', fn = 'mean')),
               columns = c('num', 'currency'),
               groups = 'grp_a', 
               fmt = ~ fmt_number(., use_seps = TRUE)) |>
  grand_summary_rows(fns =list(list(label = 'grand total', fn = 'sum')),
                     columns = c('num', 'currency'),
                     fmt = ~ fmt_number(., use_seps = TRUE)) |>
  tab_footnote(footnote = "This is a footnote. With a second line.",
               locations = cells_body(columns = 'time', rows = 3L)) |>
  tab_footnote(footnote = "This is a footnote in the column labels.",
               locations = cells_column_labels(columns = 'fctr')) |>
  tab_source_note(source_note = 'NOTES:  A mtcars example.') |>
  # Table formatting with tab_style
  tab_style(style = cell_text(decorate = 'overline'),
            locations = cells_stubhead()) |>
    tab_style(style = cell_text(transform = 'uppercase'),
            locations = cells_column_labels(columns = c('num', 'fctr', 'datetime'))) |>
    tab_style(style = gt::cell_text(style = 'italic'),
            locations = cells_column_spanners(spanner = 'a1')) |>
  
  # Body styles
  tab_style(style = cell_text(size = 20,
                              decorate = 'underline',
                              color = 'red'),
            locations = cells_body(columns = 'time',
                                   rows = c(3:4))) |>
  tab_style(style = cell_text(indent = px(20),
                              weight = 'bold'),
            locations = cells_body(columns = 'char',
                                   rows = c(2L, 4L, 5L))) |>
  tab_style(style = cell_text(indent = px(15),
                              style = 'oblique'),
            locations = cells_stub(rows = c(2L, 4L, 5L))) |>
  tab_style(style = cell_text(size = 20L,
                              color = '#0000FF'),
            locations = cells_body(columns = 'fctr')) |>
  tab_style(style = list(cell_text(weight = 'bold'),
                         cell_fill(color = '#CCCCFF')),
            locations = cells_row_groups(groups = 'grp_b')) |>
  tab_style(style = cell_text(size = 'x-small'),
            locations = cells_body(columns = 'datetime')) |>
  tab_style(style = list(cell_text(color = '#FFFFFF'),
                         cell_fill(color = '#AA0000')),
            locations = cells_stub()) |>
  # Footnoe and source note styles
  tab_style(style = cell_text(size = 8,
                              style = 'italic'),
            locations = cells_source_notes()) |>
  tab_style(style = cell_text(weight = 'bold'),
            locations = cells_footnotes()) |>
  
  # Summary styles
  tab_style(style = cell_fill(color = '#00FF00'),
            locations = cells_summary(groups = 'grp_a',
                                      columns = c('num', 'currency'),
                                      rows = 2L)) |>
  tab_style(style = cell_text(color = '#00FF00'),
            locations = cells_stub_summary(groups = 'grp_a',
                                           rows = 1L)) |>

  # Grand summary styles
  tab_style(style = cell_text(transform = 'capitalize',
                              weight = 'bold'),
            locations = cells_stub_grand_summary()) |>
  tab_style(style = cell_fill(color = '#AAAAAA'),
            locations = cells_grand_summary()) |>
  tab_options(table.font.size = px(12))

```

For reference, this is how the table appears in the HTML output, which reflects all of the formatting changes and shows how the table "should" be displayed.

tab_style-html

The screen grab below shows how the same table is displayed in the PDF output.  

tab_style-latex-before

There are several changes that are reflected in the HTML table but not the PDF.

1. None of the font size changes, made to the entire table by `tab_options` or to individual cells by `tab_style`, have been implemented.
2. The heading of the first spanner is not italicized.
3. The stubhead does not have an overline.
4. All of the column labels are lowercase (some should be uppercase).
5. Neither cells in the char column nor the stub have been indented.
6. Cell text coloring works in the body (as in the fctr column) but not in other parts of the table (like the stub of the summary row for "Total").
7. Cell background coloring works in the stub (and I think in the body, though that's not shown here), but not in the summary rows or group labels.
8. Underlining in the body (time column) is not implemented.
9. The stub for the grand summary row is neither sentence case nor bolded.
10. Formatting for the footnotes and source notes are not implemented.

The code in this pull request incorporates all of these changes.  The same Quarto document, when using the modified code, produces a table in the PDF output that looks like the following.

tab_style-latex-after

## What the changes do

I've created a new function, `apply_cell_styles_l`, that takes a block of content to be included in a LaTeX table and applies the appropriate formatting depending on where the content will appear.  That function is now called from the code that generates all the parts of a LaTeX table (i.e., the body, stub, stubhead, column labels, footnotes, source notes, etc.).  This function calls a sequence of other functions with the naming convention `.apply_style_PARAMETER_l` where PARAMETER refers to a parameter of the `cell_text` or `cell_fill` functions, such as `.apply_style_fontsize_l` or `.apply_style_decorate_l`.  Going forward, this should make adding additional formatting or maintaining existing formatting somewhat easier.

Almost all of the changes in this pull request affect code that is only called downstream of `as_latex()` (and _none_ of the changes affect code that implements other table types).  However, there are two changes that occur earlier that I want to draw your attention to.

First, in cells with footnotes, I wanted to prevent any cell-specific formatting from altering the appearance of the footnote mark.  In the Latex example above for the current code, note that in the third row of the time column, the footnote mark is shown as red and, in the HTML code it is also underlined.  I am assuming that is not intentional behavior (if it is, I respectively suggest the footnote mark in the cell should appear identical to the mark under the table).  The footnote mark is added to the cell content during the execution of `build_data`.  I have altered the function `paste_footnote_latex` to alter this behavior.  For example, a call to `build_data` currently would change the content for the third row of column time to be "\\textsuperscript{2}15:45".  The code now changes the content to be "15:45%%%left:2".  That is the presence of the footnote is denoted by "%%%%" followed by the position of the footnote market ("left" or "right") and, after a colon, the mark itself. This new encoding allows the `apply_cell_styles_l` function to separate the cell content from the footnote mark, apply any cell-specific formatting only to the content, and then put the formatted context back together with the mark.  The result, as you can see in the table pictured above of the new code, is that the footnote mark is unaffected by any changes to the formatting of the cell content itself.

Second, several of the format functions, by default, placed cell output in LaTeX's math mode.  This behavior limits the extent to which a cell's content can be reformatted (i.e., bolded, underlined).  In the vast majority of cases, this is unnecessary.  This code submission alters this behavior by removing math mode from these function calls.  This is a quick change to make to the code (I deleted three lines in the `process_text` function that imposed math mode for LaTeX output) that required me to change 200+ test results.  I went through all of these by hand (I'm not kidding) to verify that I wasn't missing any cases where math mode was necessary or even helpful.  In the vast majority of cases, results were returned as just numbers in the math model (i.e., $1234.56$) or as numbers with explicit text calls (i.e., $1234\\text{ppm}$.  Putting these results in math mode added nothing, while taking them out of math mode (1234.56 or 1234ppm) provides much more flexibility to format later.

There were only two cases where taking away the math mode default required more significant changes.

1. Content displaying fractions relied on math mode.  For example, 0.5 was being displayed as ${}^{1}\\!/{}_{2}$. This coding is specific to math mode. I have changed the behavior of these functions to output this as \\textsuperscript{1}\\!/\\textsubscript{2}, which does literally the same thing outside of math mode.  This yields the same output with additional flexibility for formatting the content through `tab_style`.

2. Numbers in exponential notation were displayed as $3 \\times 10^{4}$. In this case, math mode is somewhat called for because the LaTeX math symbol does look cool.  I have nevertheless changed this output so it now appears as "3 $\\times$ 10\\textsuperscript{4}" which uses math mode for the necesssary part (the multiplication symbol) but allows the rest of the number to display as regular text (that can be reformatted).

To be clear, changing the default use of math mode in no way precludes users from using math mode themselves.  If a user wants to have a column display a math function that requires math mode, none of the changes I've made will prevent that.  The user won't be able to format those cells, but that's a LaTeX restriction they have to live with.

# Conclusion

Hopefully, you will find this pull request useful.  I'm happy to make changes as necessary or if this is merged to help fix any bugs that I may not have caught as they come up.

Thanks for building such a well-thought-out and useful package! 

# Related GitHub Issues and PRs

- Ref: #1472 

# Checklist

- [ x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [ x] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [ x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by rich-iannone** [comment]
I have to say, this is incredible work! I'm so thankful for all the time you put into this. Going to review this shortly.

**Comment by rich-iannone** [comment]
I tested this out locally and everything is looking great! When running the tests I found that a lot of LaTeX snapshots need updating. Below is the reporter output for the snapshot issues. Would you like to correct these by generating new snapshots? I could also take it from here if you prefer.


```
── Failed tests ───────────────────────────────────────────────────────────────────────────────────────────────
Error (test-as_latex.R:54:3): Table styles correctly applied
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─... %>% expect_snapshot() at test-as_latex.R:54:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-fmt_fraction.R:524:3): The `fmt_fraction()` function produces reproducible results for HTML output
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─... %>% expect_snapshot() at test-fmt_fraction.R:524:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-footer.R:23:3): The footer section formatting and options work well across all output formats
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─exibble_multiline %>% as_latex() %>% as.character() %>% ... at test-footer.R:23:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-group_column_label.R:141:3): Group labels as a column work well across many variations
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_1 %>% as_latex() %>% as.character() %>% expect_snapshot() at test-group_column_label.R:141:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-l_table_parts.R:36:3): A gt table contains the expected heading components
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─... %>% expect_snapshot() at test-l_table_parts.R:36:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-l_table_parts.R:102:3): A gt table contains the expected column spanner labels
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_latex %>% as_latex() %>% as.character() %>% ... at test-l_table_parts.R:102:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-l_table_parts.R:218:3): A gt table contains the expected source note
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_latex %>% as_latex() %>% as.character() %>% ... at test-l_table_parts.R:218:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-l_table_parts.R:255:3): A gt table contains the correct placement of row groups
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_latex %>% as_latex() %>% as.character() %>% ... at test-l_table_parts.R:255:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows_latex.R:22:3): Using summary rows in LaTeX tables is correct
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─... %>% expect_snapshot() at test-summary_rows_latex.R:22:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-tab_footnote.R:850:3): Footnotes with no location are rendered correctly
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─gt_footnotes_1 %>% as_latex() %>% as.character() %>% ... at test-tab_footnote.R:850:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:668:3): Using `groups = NULL` in `summary_rows()` is a deprecated option
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:668:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:709:3): Summary rows can be added to the top of any group
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:709:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:815:3): Grand summary rows can be added to the top of a table
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:815:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-tab_footnote.R:1137:3): Footnotes work with group labels in 2-column stub arrangements
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─gt_tbl %>% as_latex() %>% as.character() %>% ... at test-tab_footnote.R:1137:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:1304:3): Labels can be intrepreted from Markdown using `md()`
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:1304:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:1340:3): Groups can be formatted selectively with a formatting group directive
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:1340:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:1538:3): Formatting can be performed on summary cells in certain columns and rows
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:1538:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-summary_rows.R:2011:3): Situtations where `rowname` is a column name don't interfere with internals
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─summary_tbl_1 %>% as_latex() %>% as.character() %>% ... at test-summary_rows.R:2011:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-tab_stub_indent.R:12:3): A gt table can contain indentation in the stub
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_1 %>% as_latex() %>% as.character() %>% expect_snapshot() at test-tab_stub_indent.R:12:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)

Error (test-tab_stub_indent.R:80:3): Indentation values can be obtained from a table column
Error in `trace_back(top = getOption("testthat_topenv"), bottom = trace_env)`: Can't find `bottom` on the call tree.
Backtrace:
    ▆
 1. ├─tbl_6 %>% as_latex() %>% as.character() %>% expect_snapshot() at test-tab_stub_indent.R:80:3
 2. └─testthat::expect_snapshot(.)
 3.   └─testthat:::expect_snapshot_helper(...)
 4.     └─testthat::expect(...)
 5.       └─rlang::trace_back(top = getOption("testthat_topenv"), bottom = trace_env)
 6.         └─rlang:::trace_find_bottom(bottom, frames)
 7.           └─rlang::abort(msg, call = call)
 ```

**Comment by kbrevoort** [comment]
@rich-iannone 

Apologies for the PR not passing these tests.  After committing the test updates I made a small code change when creating the screen grabs to in the PR message.  I didn't think it would necessitate changing the snapshots. 

This has raised an issue about the PR that I'd like your guidance on before I either update the snapshots or change the code.

The change I meant to make was to handle cases where the user explicitly sets a table-wide font size using tab_options, such as `gt1 <- gt(exibble) |> tab_options(table.font.size = px(16))`, the `as_latex` function would change the font size to 12pt immediately before beginning the longtable environment.   What I did not anticipate is that if the table was silent about the value of table.font.size, as in `gt2 <- gt(exibble)`, or explicitly set to NULL as in `gt3 <- gt(exibble) |> tab_options(table.font.size = NULL)` (which is the default parameter value in the help file for `tab_options`) the value of table.font.size is set to the default value of 12pt.  The code in the PR explicitly sets this value of table.font.size. 

If that's what you want, I'll update the tests.  But as a user, I think my preference would be that unless I explicitly set a value for table.font.size, the LaTeX code should remain silent about the font size used for the table and allow its value (and the other font characteristics) to be determined by the document where it appears.  

If you want to go with the latter approach, it will require changing how the table.font.size parameter is stored in the gt_tbl object, which would have implications beyond the LaTeX portion of the code.

I'm happy to implement either approach.  How would you like me to proceed?

Thanks!

**Comment by rich-iannone** [comment]
@kbrevoort I think we should go with the former/preferred/least-surprising approach with the font size. And thanks again for doing all this work, I know it's a lot but many people are going to love the results of this PR.

**Comment by rich-iannone** [comment]
Also @kbrevoort , if you'd like to, you should add yourself to the authors list in DESCRIPTION. You've done a lot of great work and you really fill the role of LaTeX output expert here.

**Comment by kbrevoort** [comment]
@rich-iannone If I can pester you with a final question on this, is https://posit.co/individual-contributor-agreement/ the CLA I need to sign?  If not, can you point me to where I can find it?  I think that's the last thing I need to do.

Thanks!  And thank you for making me an author on the package.  I appreciate the acknowledgement!

**Comment by rich-iannone** [comment]
Thank you very much for all the work done here! That link does have the CLA as a PDF. If you could download, fill out, and send it to me at rich@posit.co I'd really appreciate it.

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by capnrefsmmat** [comment]
> But as a user, I think my preference would be that unless I explicitly set a value for table.font.size, the LaTeX code should remain silent about the font size used for the table and allow its value (and the other font characteristics) to be determined by the document where it appears.

Just to comment on this as a user who just encountered it: I'd much prefer this behavior as well.

I recently upgraded to the latest gt and discovered my tables are now too large in PDF output, because gt is inserting `\fontsize{12.0pt}{14.4pt}\selectfont` before each table. To me that's surprising: the least surprising approach would be for tables to be the default body text size in the LaTeX document, whatever that may be. gt should only override that if I explicitly ask for it.

As this is a large Quarto project spread across multiple files, the current behavior means I have to figure out how to manually set the correct font size each time I load gt, and I'd have to go change all of them if I change the font size of my PDF.

(Of course, I'd prefer the same behavior in HTML output too, but at least I can deal with that in CSS...)

**Comment by rich-iannone** [comment]
@capnrefsmmat I'm coming around to this as well. Would you be willing to open a new issue here (along with @kbrevoort 's quote comments)?

**Comment by capnrefsmmat** [comment]
Sure, I opened #1852 with the context.

**Pull request merged**
