### PR TITLE
LaTeX output invalid with `tab_header` when subtitle is empty or NULL

### PR DESCRIPTION
**Pull request by vincentarelbundock**
The notebook pasted below does not knit with current `gt` master. The problem is that `create_heading_component` only checks if `subtitle` is an element of `heading` before appending to the header. But when `tab_header(subtitle = '')` or `tab_header(subtitle = NULL)`, it adds some useless stuff to the caption, which breaks LaTeX compile.

When there is a title but no subtitle, `tab_header` records subtitle as an empty string rather than NULL. I don't understand why, but the comment in `tab_header` suggests this empty string might be important elsewhere:

https://github.com/rstudio/gt/blob/master/R/table_parts.R#L37

```
---
title: "heading latex pull request"
header-includes:
    - \usepackage{longtable}
    - \usepackage{booktabs}
    - \usepackage{subcaption}
output:
  pdf_document: default
---

```{r}
library(gt)
library(dplyr)

data.frame('a'=1:2, 'b'=c('k', 'z')) %>%
  gt() %>% 
  tab_header(title = 'car', subtitle = NULL)
```

```

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks for looking into this so quickly. I'll try to make sure there are no side effects like this if/when I open another PR.

I made the two requested changes, ran `git commit --amend`, and force pushed so you get a clean log. The `testthat` suite passes without errors or warnings on my machine.

**Comment by vincentarelbundock** [comment]
I also emailed the signed form.

**Comment by vincentarelbundock** [comment]
@rich-iannone 

I mishandled some git branching thing on my end and ended up modifying this PR. This adds a new `label` argument to `tab_header` for cross-referencing and table numbering in LaTeX.

I also added a test.

Sorry to force you to look at this again.

**Comment by vincentarelbundock** [comment]
``` r
library(gt)
tab <- data.frame('a' = 1:2, 'b' = 3:4) %>%
       gt() 

# no caption when nothing is supplied
tab %>% as_latex() %>% cat()
#> \captionsetup[table]{labelformat=empty,skip=1pt}
#> \begin{longtable}{rr}
#> \toprule
#> a & b \\ 
#> \midrule
#> 1 & 3 \\ 
#> 2 & 4 \\ 
#> \bottomrule
#> \end{longtable}

# \caption*{ when no label is supplied
tab %>% tab_header(title = 'test title', 
                   subtitle = 'test subtitle') %>%
    as_latex() %>% cat()
#> \captionsetup[table]{labelformat=empty,skip=1pt}
#> \begin{longtable}{rr}
#> \caption*{
#>   \large test title \\ 
#>   \small test subtitle
#> } \\
#> \toprule
#> a & b \\ 
#> \midrule
#> 1 & 3 \\ 
#> 2 & 4 \\ 
#> \bottomrule
#> \end{longtable}

# \caption{ when a label is supplied
tab %>% tab_header(title = 'test title', 
                   subtitle = 'test subtitle',
                   label = 'tab_label') %>% 
    as_latex() %>% cat()
#> \captionsetup[table]{labelformat=default,skip=1pt}
#> \begin{longtable}{rr}
#> \caption{
#>   \large test title \\ 
#>   \small test subtitle
#>   \label{tab_label}
#> } \\
#> \toprule
#> a & b \\ 
#> \midrule
#> 1 & 3 \\ 
#> 2 & 4 \\ 
#> \bottomrule
#> \end{longtable}

tab %>% tab_header(title = 'test title', 
                   label = 'tab_label') %>% 
    as_latex() %>% cat()
#> \captionsetup[table]{labelformat=default,skip=1pt}
#> \begin{longtable}{rr}
#> \caption{
#>   \large test title
#>   \label{tab_label}
#> } \\
#> \toprule
#> a & b \\ 
#> \midrule
#> 1 & 3 \\ 
#> 2 & 4 \\ 
#> \bottomrule
#> \end{longtable}

tab %>% tab_header(title = ' ', label = 'tab_label') %>% 
    as_latex() %>% cat()
#> \captionsetup[table]{labelformat=default,skip=1pt}
#> \begin{longtable}{rr}
#> \caption{
#>   \large  
#>   \label{tab_label}
#> } \\
#> \toprule
#> a & b \\ 
#> \midrule
#> 1 & 3 \\ 
#> 2 & 4 \\ 
#> \bottomrule
#> \end{longtable}
```

<sup>Created on 2019-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by vincentarelbundock** [comment]
screen shot 2019-01-26 at 9 13 57 am

**Comment by vincentarelbundock** [comment]
Now I'm wondering if `label` shouldn't be in `tab_options` instead of `tab_header`. In LaTeX, it's called in the caption, but it might be better to just gather *all* options in one place.

**Comment by eipi10** [comment]
I installed this version of `gt` in order to try out cross-referencing, but found that although the table rendered, only a `??` appeared in the main text where I tried to cross-reference the table. Here's a reproducible example:

First, in R I installed (or at least I hope I installed) the version of the package with the updates described above.

`devtools::install_github("rstudio/gt", ref="eff3be7384365a44459691e49b9b740420cd0851")`

Then I created the `rmarkdown` document below:
``````
---
output: 
  bookdown::pdf_document2
toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(gt)
```

You can see in Table \@ref(tab:tab1) that this is the famous `mtcars` data frame.

```{r}
mtcars %>% 
  slice(1:2) %>% 
  gt() %>% 
  tab_header(title="First two rows of mtcars",
             label="tab1")
```

And here's Table \@ref(tab:tab2) to demonstrate that cross-reference works with `kable`.

```{r tab2}
kable(mtcars[1:2, ], caption="Another table", booktabs=TRUE)
```
``````

The PDF output is below. Note the `Table ??` where `Table 1` would be if cross-referencing were working as desired. The tables are also in the wrong order, which I think is also related to cross-referencing not working properly for the first table.

screen shot 2019-02-13 at 2 47 07 pm

**Comment by vincentarelbundock** [comment]
You need to add the prefix to your label: `label = 'tab:tab1'`.

The table order is probably a result of some table options like `[ht!]` or something that `kable` adds automatically. The `gt` output is quite bare in this regard.

screenshot from 2019-02-13 18-19-16

**Comment by eipi10** [comment]
Thanks very much Vincent. That did the trick.

**Comment by vincentarelbundock** [comment]
It's an interesting design question though. I personally don't like that `kable` adds prefixes to my labels willynilly. But I could certainly see an argument for conformity of `gt` with `kable` standard.

**Comment by kevinykuo** [comment]
Could we move this forward/anything I can do to help? I'm looking for bookdown/html support for cross referencing and it might make sense to have this merged first.

**Comment by haohua** [comment]
Hi guys, is this PR finished?  
The PR has been opened since 12 month ago. 
The cross-referencing is the one I am very interested in.

**Comment by vincentarelbundock** [comment]
> Hi guys, is this PR finished?
> The PR has been opened since 12 month ago.
> The cross-referencing is the one I am very interested in.

My guess is that this PR won't be merged. This is only a temporary hack, and LaTeX support is going to be worked on at a later date (not sure when).

In the meantime, you can perhaps roll your own function to do this, for example:

https://github.com/vincentarelbundock/modelsummary/blob/master/R/clean_latex.R#L36

Of course, we're all hoping for more complete LaTeX support, but developers are obviously under time constraints, etc.

**Comment by haohua** [comment]
@vincentarelbundock  thank you so much Vincent.  

Now i can render gt table into my pdf file . 
However, my table is too wide. do you know if there is any way to shrink the gt table to fit in the page? 
Something like   "scale_down" in kableEtra? 
kable(iris[1:5,],
          format = "latex", booktabs = TRUE) %>%
          kable_styling(latex_options = "scale_down")

**Comment by vincentarelbundock** [comment]
I don't think `gt` has that feature at the moment, unfortunately.

**Comment by OAshkar** [comment]
+1 Latex support would be very great. Why not as_latex has a clean parameters for caption, location and label?

**Comment by jimbotyson** [comment]
I have installed a version of gt() from

devtools::install_github("rstudio/gt", ref="eff3be7384365a44459691e49b9b740420cd0851")

in order to use the option for a label/caption, like this:

```
mtcars %>%
slice(1:2) %>%
gt() %>%
tab_header(title="First two rows of mtcars", label="tab:tab1")
```

This is taken from an example on the package github page.

I've checked other examples and I can't see that I'm doing anything wrong, but when I render this (it's in a RMarkdown document), I consistently see this error:

```
Error in tab_header(., title = "First two rows of mtcars", label = "tab:tab1") :
unused argument (label = "tab:tab1")
```

I can't see where I'm going wrong and any help would be appreciated.

**Pull request closed without merging**
