### PR TITLE
Add support for groups in `opt_interactive()` via reactable `groupBy`

### LINKED ISSUE #1705: `groupname_col` disappears with `opt_interactive()`
With gt 0.10.0.9000,

we can have 

```r
d <- mtcars |> dplyr::slice_head(n = 10)
```

| row_group_as_columns = FALSE | row_group_as_columns = TRUE |
|--------|--------|
| `gt::gt(d, groupname_col = "vs")`  |  `gt::gt(d, groupname_col = "vs", row_groups_as_columns = TRUE)` |
| image |  image |
 
Currently, `opt_interactive()` hides the `vs`  `groupname_col` column regardless.

## Here is my suggestion with `reactable::reactable()`

```r
# use `colDef()` to hide column name
# use rownames = FALSE since we are using a different column as row names
# From https://github.com/glin/reactable/issues/94
grp_fn  = reactable::JS("
      function(cellInfo) {
        return cellInfo.value
      }")

mtcars |> dplyr::slice(1:10)  |>reactable::reactable(groupBy = "vs",defaultExpanded = T, rownames = FALSE, columns = list(vs = reactable::colDef(name = "", grouped = grp_fn)))
```
image

I don't see a good solution for `row_group_as_columns = T` as I couldn't find an example of reactable merging a column, but would still be an improvement.

### PR DESCRIPTION
**Pull request by olivroy**
# Summary

* Use `defaultExpanded = TRUE` + `groupBy` in `reactable::reactable()`
* FIddle to add the group data to `data_tbl` in `render_as_i_html()`

Here is an implementation of showing `groupname_col`. This feels incomplete, but wanted to get the ball rolling, 

Basically, 

```r
mtcars |> dplyr::slice_head(n = 10) |> gt(groupname_col = "vs") |> opt_interactive()
```

Now (hide group cols):
image

This PR:
image

Let me know if you can think of how this could be improved.

I think this opens the door to supporting `summary_rows()`.

Is there a way to test (at least visually the interactive output. Maybe a new vignette that contains just examples could be created?

Just to visually be able to see what's going on, and if regressions are not introduced by my fiddling.
 
## Limitations

* Wrong number of rows shown
* No merged column groups
* Wrong row total number
* Still no summary_rows
* ignores a couple things probably, such as the css of groups. This could easily be added if necessary
* `cols_hide()` respected?

## Advantage

* Actually show group cols
* expanding cols

# Related GitHub Issues and PRs

- Ref: fixes #1705

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [x] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by rich-iannone** [comment]
I totally agree with this implementation! As for testing, the article/vignette route might be the only practical way to go.

**Comment by olivroy** [comment]
Sweet. I can look into doing this afterwards!

**Review by rich-iannone — APPROVED** [review]
LGTM

**Comment by rich-iannone** [comment]
Everything looks good here. I understand you want to follow up with further changes in other PRs. In that case is this PR ready to merge?

**Comment by olivroy** [comment]
Yes. This PR is good to go!

**Pull request merged**
