### PR TITLE
Allow selection in interactive tables

### LINKED ISSUE #354: shiny get selected row from GT
It would be great if GT could be used in Shiny as way for reactive inputs. That is, a user clicks on a row in a GT and passes data from that row as a reactive input. Datatable has this capability. When user clicks a row in a datatable, we can access the selected row with:
input$tableId_rows_selected
see here:
https://stackoverflow.com/questions/28274584/get-selected-row-from-datatable-in-shiny-app

Thanks very much!

### LINKED ISSUE #1368: row selection reactive variable needed for shiny app
## Prework
couldn't find any similar request in the issue list

## Proposal

There is a `DT` package in R that is adopted from JS datatable package. This means a lot of its features are hidden and have to be passed through nested list(), which is very hard to remember. The only reason we still use DT package is the `input$tabname_rows_selected` reactive variable that is not available in `gt` (as yet). 

I suggest `gt` package to also allow row selection to be detected in a shiny app as an `input$..` variable. Then gt would be a compelling replacement of the DT package.

### PR DESCRIPTION
**Pull request by jonthegeek**
# Summary

Add an option `ihtml_selection` (default NULL, can be "single" or "multiple") to enable selection in interactive gt tables. When this is on, make it available as an input in Shiny.

# Related GitHub Issues and PRs

- Closes #354.
- Closes #1368.

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [x] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by jonthegeek** [comment]
So far I've just set up the option. I need to add tests, and then move on to the Shiny side.

**Comment by jonthegeek** [comment]
A test app to see it in action:

```r
# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
# Or use the blue button on top of this file
library(shiny)
pkgload::load_all(".", helpers = FALSE, attach_testthat = FALSE)

gt_tbl <-
  gtcars |>
  gt() |>
  fmt_currency(columns = msrp, decimals = 0) |>
  cols_hide(columns = -c(mfr, model, year, mpg_c, msrp)) |>
  cols_label_with(columns = everything(), fn = toupper) |>
  data_color(columns = msrp, method = "numeric", palette = "viridis") |>
  sub_missing() |>
  opt_interactive(use_compact_mode = TRUE, selection = "multiple")

ui <- fluidPage(
  gt_output(outputId = "table"),
  verbatimTextOutput("selected")
)

server <- function(input, output, session) {
  output$table <- render_gt(expr = gt_tbl)
  output$selected <- renderPrint({
    input$table
  })
}

shinyApp(ui = ui, server = server)
```

Add this to preview an alternate UI that I'm playing with (I'll probably add something like this as a separate function):

```r
gt_tbl <-  opt_css(gt_tbl, "
/* Hide the selection column */
.rt-td-select {
  display: none;
}

/* Style for selected rows */
.rt-tr-selected {
  background-color: black;
  color: white;
}")
```

I'm hoping I can learn a better way to wait for the tables to be "done" via the Discord!

**Comment by jonthegeek** [comment]
Pulling this back to draft to add an update function. If we're highlighting selections, I want to be able to set the highlight.

**Comment by jonthegeek** [comment]
@rich-iannone I fixed the pkgdown issue. Let me know what else you need!

**Comment by jonthegeek** [comment]
Found another corner: sorting sends an event that causes the selection to update (potentially to "nothing selected"), which shouldn't be seen as a change. Fixing.

**Comment by jonthegeek** [comment]
Adding pre-selected values is proving tricky using the option system. I don't see a way for an option to be an integer or logical vector, and I'm not sure it would fit there even if it were possible. I can work around that not being there for my use case, so I think I'd rather hold onto that for a future PR.

Which is all to say... I think this is ready again!

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by jonthegeek** [comment]
@rich-iannone Sorry about that! Evidently I never ran that suite of tests after I renamed the fields. I was trying to make room to pass in pre-selected values, and forgot to fix the test after I rolled back *almost* everything (other than the name of the field).

Should be good now, for real this time!

**Comment by rich-iannone** [comment]
@jonthegeek thanks for all your work on this!

**Pull request merged**
