### PR TITLE
Decimal alignment with `cols_align_decimal()`

### PR DESCRIPTION
**Pull request by rich-iannone**
This adds the `cols_align_decimal()` function, which is to be used for lining up numeric values by the decimal mark. The function ensures that columns targeted are right-aligned, that accounting notation is supported, and that footnote marks don't interfere. 

Fixes: #139 
Fixes: https://github.com/rstudio/gt/issues/144
Fixes: https://github.com/rstudio/gt/issues/560
Fixes: https://github.com/rstudio/gt/issues/673

### CODE REVIEW

**Comment by cscheid** [comment]
I know some people who literally refuse to use anything but LaTeX tables exactly because of this feature!

**Comment by cscheid** [comment]
@domoritz Sorry to randomly tag you on this, but check out what's coming to quarto's tables soon! 😍 https://github.com/rstudio/gt/pull/1058/files#diff-0561d116b26297ef34a596107e310c46f00d108472133cc5468dc644fe0e124f

**Review by cscheid — APPROVED** [review]
This looks excellent.

**Comment by domoritz** [comment]
😍 that's awesome. Thank you for randomly tagging me.

**Comment by steveputman** [comment]
This is great, @rich-iannone! 

It's fairly common, when using `accounting = TRUE`, that numbers are rounded (so `decimals = 0`). That combination of options (unless `drop_trailing_dec_mark = FALSE` is also used) doesn't align properly, which obviously makes sense given that there are no decimals for `cols_align_decimal()` to attack. 

Do you think there's any way to address that combination of options (for example by (a) faking the decimal by imputing the `drop_trailing_dec_mark = FALSE` option, running `align_to_char()`, then stripping out the decimal or (b) applying the original approach of inserting an invisible parenthesis after nonnegative numbers)? Happy to take a stab but not sure of the best approach.

Thanks!

``` r
library(gt)

dplyr::tibble(
  char = LETTERS[1:8],
  num = c(1.2, -33.52, 9023.2, -283.527, 0.401, -123.1, NA, 41)) |> 
  gt() |> 
  tab_header("fmt_currency / accounting = TRUE / decimals = 0") |> 
  fmt_currency(num, accounting = TRUE, decimals = 0) |> 
  cols_align_decimal()
```

<div id="cgxvxxiaoe" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>fmt_currency / accounting = TRUE / decimals = 0</td>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="char">char</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="num">num</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="char" class="gt_row gt_left">A</td>
<td headers="num" class="gt_row gt_right">    $1 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">B</td>
<td headers="num" class="gt_row gt_right"> ($34 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">C</td>
<td headers="num" class="gt_row gt_right">$9,023 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">D</td>
<td headers="num" class="gt_row gt_right">($284 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">E</td>
<td headers="num" class="gt_row gt_right">    $0 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">F</td>
<td headers="num" class="gt_row gt_right">($123 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">G</td>
<td headers="num" class="gt_row gt_right">NA</td></tr>
    <tr><td headers="char" class="gt_row gt_left">H</td>
<td headers="num" class="gt_row gt_right">   $41 </td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request merged**
