### PR TITLE
Update as_latex() documentation to include steps to take to ensure dependencies are present when rendering the document.

### PR DESCRIPTION
**Pull request by coatless**
When I was working with a custom beamer template, the `as_latex()` function didn't add the appropriate package dependencies to the header. I've added a bit of documentation to emphasize the requirements and steps to take to ensure smooth sailing.

Screen Shot 2020-06-30 at 1 06 08 PM

### CODE REVIEW

**Comment by coatless** [comment]
@rich-iannone any thoughts on this one?

**Review by rich-iannone — APPROVED** [review]
lgtm!

**Comment by rich-iannone** [comment]
@coatless sorry for the delay on this. It all looks good but for reasons I cannot understand, this branch is not visible like all the other branches that have open PRs. Could you perhaps update the branch or, failing that, make a new PR with exactly the same changes? Thanks!

**Comment by coatless** [comment]
@rich-iannone done in #1022

**Pull request closed without merging**
