### PR TITLE
Issue 1465

### PR DESCRIPTION
**Pull request by kbrevoort**
# Summary

This pull request addresses two previously-reported bugs associated with outputting tables to LaTeX.  

1.   Issue #1465:   Fixes an issue where table columns specified with the `pct` function cause LaTeX compilation errors.   The error is caused by the fact that specifying `cols_width(everything() ~ pct(20))` specifies the column width in LaTeX as "20%".  Since % is the comment symbol in LaTeX, this produces a compilation error.  The code has been changed so that the column width in LaTeX will be output as "0.2\linewidth" if the table width is unspecified (in which case each column will take up 20% of the available width) or 0.2 times the specified table width.
2.  Issue #119 (and duplicate issue #329):   Uses the user-supplied table widths to establish the LaTeX tables widths.  The code works with user-specified widths expressed as percentages (i.e., `tab_options(table.width = pct(100))`) or as specific units (i.e., `tab_options(table.width = '400px')`).  Table widths are established using the specified LaTeX lengths \LTleft and \LTright.  Extra space to fill out the table width, if necessary, is added in between the columns by setting `\extracolsep to \fill. (The code also creates two temporary length measures in LaTex, \holdLTleft and \holdLTright which record the existing length values of \LTleft and \LTright before setting them to the user-specified lengths for the table.  After the longtable environment is ended, the preexisting values of \LTleft and \LTright are restored.

# Related GitHub Issues and PRs

- Issue #1465 
- Issue #119 
- Issue #329 

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [x] I have listed any major changes in the [NEWS](https://github.com/rstudio/gt/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/gt/tree/master/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thank you so much for submitting this PR! I'll review this PR pretty soon.

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by rich-iannone** [comment]
@kbrevoort Before merging, could you fill out the CLA?

**Comment by kbrevoort** [comment]
@rich-iannone, can you point me to where I can find the CLA?  I haven't been able to figure out how to access it.

**Comment by briandk** [comment]
@kbrevoort @rich-iannone - I'm just bumping this because it seems the only thing holding it up is accepting the contributor license agreement(?)

**Pull request merged**
